export const popularCountries = [
  { Country_Name: "United States", Code: "US", Language: "English" },
  { Country_Name: "China", Code: "CN", Language: "Mandarin" },
  { Country_Name: "India", Code: "IN", Language: "Tamil" },
  { Country_Name: "Germany", Code: "DE", Language: "German" },
  { Country_Name: "France", Code: "FR", Language: "French" },
  { Country_Name: "Italy", Code: "IT", Language: "Italian" },
  { Country_Name: "Russia", Code: "RU", Language: "Russian" },
  { Country_Name: "Brazil", Code: "BR", Language: "Portuguese" },
  { Country_Name: "South Korea", Code: "KR", Language: "Korean" },
  { Country_Name: "Spain", Code: "ES", Language: "Spanish" },
  { Country_Name: "Turkey", Code: "TR", Language: "Turkish" },
  { Country_Name: "United Arab Emirates", Code: "AE", Language: "Arabic" },
  { Country_Name: "South Africa", Code: "ZA", Language: "Afrikaans" },
  { Country_Name: "Indonesia", Code: "ID", Language: "Indonesian" },
  { Country_Name: "Japan", Code: "JP", Language: "Japanese" },
  { Country_Name: "Mexico", Code: "MX", Language: "Spanish" },
  { Country_Name: "United Kingdom", Code: "GB", Language: "English" },
  { Country_Name: "Australia", Code: "AU", Language: "English" },
  { Country_Name: "Argentina", Code: "AR", Language: "Spanish" },
  { Country_Name: "Canada", Code: "CA", Language: "English, French" },
  { Country_Name: "Egypt", Code: "EG", Language: "Arabic" },
  { Country_Name: "Nigeria", Code: "NG", Language: "English" },
  { Country_Name: "Vietnam", Code: "VN", Language: "Vietnamese" },
  { Country_Name: "Thailand", Code: "TH", Language: "Thai" },
  { Country_Name: "Saudi Arabia", Code: "SA", Language: "Arabic" },
  { Country_Name: "Malaysia", Code: "MY", Language: "Malay" },
  { Country_Name: "Pakistan", Code: "PK", Language: "Urdu" },
  { Country_Name: "Philippines", Code: "PH", Language: "Filipino" },
  { Country_Name: "South Korea", Code: "KR", Language: "Korean" },
  { Country_Name: "Egypt", Code: "EG", Language: "Arabic" },
  { Country_Name: "Israel", Code: "IL", Language: "Hebrew" },
  { Country_Name: "Poland", Code: "PL", Language: "Polish" },
  { Country_Name: "Greece", Code: "GR", Language: "Greek" },
];
