const popularCountries = [
  { Country_Name: "United States", Code: "US" },
  { Country_Name: "China", Code: "CN" },
  { Country_Name: "India", Code: "IN" },
  { Country_Name: "United Kingdom", Code: "GB" },
  { Country_Name: "Germany", Code: "DE" },
  { Country_Name: "France", Code: "FR" },
  { Country_Name: "Italy", Code: "IT" },
  { Country_Name: "Japan", Code: "JP" },
  { Country_Name: "Canada", Code: "CA" },
  { Country_Name: "Australia", Code: "AU" },
  { Country_Name: "Russia", Code: "RU" },
  { Country_Name: "Brazil", Code: "BR" },
  { Country_Name: "South Korea", Code: "KR" },
  { Country_Name: "Mexico", Code: "MX" },
  { Country_Name: "Spain", Code: "ES" },
  { Country_Name: "Turkey", Code: "TR" },
  { Country_Name: "Saudi Arabia", Code: "SA" },
  { Country_Name: "United Arab Emirates", Code: "AE" },
  { Country_Name: "South Africa", Code: "ZA" },
  { Country_Name: "Indonesia", Code: "ID" },
];
