export const popularCountries = [
  { id: "1", Country_Name: "United States", Code: "US", Language: "English" },
  { id: "2", Country_Name: "China", Code: "CN", Language: "Mandarin" },
  { id: "3", Country_Name: "India", Code: "IN", Language: "Tamil" },
  { id: "4", Country_Name: "Germany", Code: "DE", Language: "German" },
  { id: "5", Country_Name: "France", Code: "FR", Language: "French" },
  { id: "6", Country_Name: "Italy", Code: "IT", Language: "Italian" },
  { id: "7", Country_Name: "Russia", Code: "RU", Language: "Russian" },
  { id: "8", Country_Name: "Brazil", Code: "BR", Language: "Portuguese" },
  { id: "9", Country_Name: "South Korea", Code: "KR", Language: "Korean" },
  { id: "10", Country_Name: "Spain", Code: "ES", Language: "Spanish" },
  { id: "11", Country_Name: "Turkey", Code: "TR", Language: "Turkish" },
  {
    id: "12",
    Country_Name: "United Arab Emirates",
    Code: "AE",
    Language: "Arabic",
  },
  { id: "13", Country_Name: "South Africa", Code: "ZA", Language: "Afrikaans" },
  { id: "14", Country_Name: "Indonesia", Code: "ID", Language: "Indonesian" },
  { id: "15", Country_Name: "Japan", Code: "JP", Language: "Japanese" },
  { id: "16", Country_Name: "Mexico", Code: "MX", Language: "Spanish" },
  { id: "17", Country_Name: "United Kingdom", Code: "GB", Language: "English" },
  { id: "18", Country_Name: "Australia", Code: "AU", Language: "English" },
  { id: "19", Country_Name: "Argentina", Code: "AR", Language: "Spanish" },
  { id: "20", Country_Name: "Canada", Code: "CA", Language: "English, French" },
  { id: "21", Country_Name: "Egypt", Code: "EG", Language: "Arabic" },
  { id: "22", Country_Name: "Nigeria", Code: "NG", Language: "English" },
  { id: "23", Country_Name: "Vietnam", Code: "VN", Language: "Vietnamese" },
  { id: "24", Country_Name: "Thailand", Code: "TH", Language: "Thai" },
  { id: "25", Country_Name: "Saudi Arabia", Code: "SA", Language: "Arabic" },
  { id: "26", Country_Name: "Malaysia", Code: "MY", Language: "Malay" },
  { id: "27", Country_Name: "Pakistan", Code: "PK", Language: "Urdu" },
  { id: "28", Country_Name: "Philippines", Code: "PH", Language: "Filipino" },
  { id: "29", Country_Name: "South Korea", Code: "KR", Language: "Korean" },
  { id: "30", Country_Name: "Egypt", Code: "EG", Language: "Arabic" },
  { id: "31", Country_Name: "Israel", Code: "IL", Language: "Hebrew" },
  { id: "32", Country_Name: "Poland", Code: "PL", Language: "Polish" },
  { id: "33", Country_Name: "Greece", Code: "GR", Language: "Greek" },
];
